#!/usr/bin/python3

import argparse
import sys
import urllib.request

import html5_parser
import html5lib

ap = argparse.ArgumentParser()
ap.add_argument("inputs", nargs="+", help="URLs or files")
args = ap.parse_args()

ret = 0

hparser = html5lib.HTMLParser(strict=True)
for inp in args.inputs:
    try:
        if "://" in inp:
            with urllib.request.urlopen(inp) as r:
                html = r.read()
        else:
            with open(inp) as f:
                html = f.read()
    except Exception as e:
        print(f"Exception {type(e).__name__} reading {inp}")
        print(e)
        ret = 1
        continue

    try:
        html5_parser.parse(html)
    except Exception as e:
        print(f"Exception {type(e).__name__} by html5_parser with {inp}")
        print(e)
        ret = 1

    try:
        hparser.parse(html)
    except Exception as e:
        print(f"Exception {type(e).__name__} by html5lib with {inp}")
        print(e)
        print(hparser.errors)
        ret = 1

sys.exit(ret)
